### ISSUE TITLE
Using a custom datum reader

### ISSUE THREAD

**Issue by Engerim** [flix-tech/avro-serde-php#26]
Hi together, first awesome work on this library and also the other 2 regarding avro. 
My Question is there any way to overwrite the datum reader with a custom datum reader or is the only possible way for now to overwrite RecordSerializer?

**Comment by tPl0ch** [comment]
@Engerim yes, currently it is only possible to override the `RecordSerializer`. Maybe I'll find some time to work on https://github.com/flix-tech/avro-serde-php/issues/3 then I'll create some more spcific interfaces to make it easier.
