### ISSUE TITLE
Update Depedency For flix-tech/confluent-schema-registry-api To 7.2

### ISSUE THREAD

**Issue by nickpoulos** [flix-tech/avro-serde-php#36]
I see that v7.2 of confluent-schema-registry-api supports Guzzle 7, any chance we can update the dependency here also? Happy to submit a PR!

**Comment by tPl0ch** [comment]
Hi @nickpoulos, the https://github.com/flix-tech/schema-registry-php-client/releases/tag/7.2.0 release of the schema registry client only contained support new caching interfaces. The Guzzle 7 support has only landed in master and is not released yet.

I'll close this issue for now, but support will land very soon!

**Comment by steveoliver** [comment]
What about now? (https://github.com/flix-tech/schema-registry-php-client/releases)
