### ISSUE TITLE
Not able to use union as map values using annotations

### ISSUE THREAD

**Issue by przwoj01** [flix-tech/avro-serde-php#40]
Hey, I found that it's not possible to do the following with annotations

This work fine with schema builder

```
$avroSchema = Schema::record()
    ->name('SubmissionReceived')
    ...
    ->field(
        'formData',
        Schema::map()
            ->values(
                Schema::union(
                    Schema::string(),
                    Schema::array()->items(Schema::string())
                )
            )
    )
    ->parse();
```

but I'm not able to do the same with annotations
```
    /**
     * @SerDe\AvroName("formData")
     * @SerDe\AvroType("map", attributes={
     *     @SerDe\AvroValues(???),
     * })
     */
    private array $formData;
```

Could someone help?

**Comment by fcoedno** [comment]
Idd that is a problem, I've just realized this now as well. The same should happen to @SerDe\AvroItems. I believe that a possible solution would be to make these annotations accept either a string for primitive types, or a @SerDe\Type annotation for complex types.

**Comment by fcoedno** [comment]
To be more precise, we are not able to define arrays or maps that contain complex types (union, records, other arrays, etc). 

I'm trying to figure out what would be the best syntax for the user, what do you think about the following one?

```
    /**
     * @SerDe\AvroName("formData")
     * @SerDe\AvroType("map", attributes={
     *     @SerDe\AvroValues({
     *          "string",
     *          @SerDe\AvroType("array", attributes={@SerDe\AvroItems("string")})
     *      }),
     * })
     */
    private array $formData;
```

**Comment by przwoj01** [comment]
Hey, thanks for quick replay.

I like what you proposed. IMO it's intuitive and would do the job. I'd also consider allowing `@SerDe\AvroType` for primitive types as well, for both `@SerDe\AvroItems` and `@SerDe\AvroValues`. Like this:

```
    /**
     * @SerDe\AvroName("formData")
     * @SerDe\AvroType("map", attributes={
     *     @SerDe\AvroValues({
     *          @SerDe\AvroType("string"),
     *          @SerDe\AvroType("array", attributes={
     *              @SerDe\AvroItems(
     *                  @SerDe\AvroType("string")
     *              )
     *          }),
     *          @SerDe\AvroType("array", attributes={
     *              @SerDe\AvroItems({
     *                  @SerDe\AvroType("int"),
     *                  @SerDe\AvroType("long")
     *              })
     *          })
     *      }),
     * })
     */
    private array $formData;
```

but to hold backward compatibility keep using the string way of defining primitive type
