### ISSUE TITLE
unpack with A* is causing trouble for specific values

### ISSUE THREAD

**Issue by gdis** [flix-tech/avro-serde-php#54]
Hello, we have problems decoding messages when the binary message contains some specific values. We noticed that when the avro schema defined has a last element an int-value, and that int value has the value of `5` or `16`, it is decoded as 0 in our application. 

After some hours of debugging, we realized that `Protocol::decode()` uses format `C%s/N%s/A*%s` for unpacking binary data. It seems `A*` is causing the problem in this specific cases. We noticed that incoming int values have a representation which are L-shifted by 1, so an int 5 has a representation of 10 -> which string representation is `\n`, since ASCII 10 is Linefeed (\n) . Now regarding to php doc https://www.php.net/manual/en/function.unpack.php unpack with formatstring `A` means:

> `A` strips all trailing ASCII whitespace (spaces, tabs, newlines, carriage returns, and NULL bytes). 

The same occurs with the value 16 (shifted-left by 1 =32 -> 32 in ASCII is SPACE => gets stripped).

NULL (ASCII 0), Tabs (ASCII 9), Carriage (ASCII 13)  are not affected, since they are odd.

Changing the formatstring to `C%s/N%s/a*%s` seems to be a fix. 

It seems to be the same issue as https://github.com/flix-tech/avro-serde-php/issues/31, but the pr https://github.com/flix-tech/avro-serde-php/pull/45 fixed only `encode`, not `decode`.

**Comment by mente** [comment]
fixed by #56, kudos to @alexeevdv . Checkout latest release 1.7.1
