### ISSUE TITLE
Schema default not taken into account when writing record

### ISSUE THREAD

**Issue by jakeBarwell** [flix-tech/avro-serde-php#66]
Not sure if this is the correct place to raise this issue but not able to raise it directly on https://github.com/flix-tech/avro-php

I may be missing something but I always get an error being thrown from https://github.com/flix-tech/avro-php/blob/master/lib/avro/datum.php#L254 when using default values and not passing any data for that field, for example:
```JSON
{
    "namespace": "test",
    "type": "record",
    "name": "AccountCreated",
    "fields": [

        {"name": "email", "type" : "string"},
        {"name": "first_name", "type" : "string"},
        {"name": "last_name", "type" : "string"},
        {"name": "test", "type": ["null", "string"], "default": null}
    ]
}
```
Should the code at https://github.com/flix-tech/avro-php/blob/master/lib/avro/datum.php#L254 be falling back to the default value of the field if the data is not provided? Something like:
```PHP
 $value = isset($datum[$field->name()]) ? $datum[$field->name()] : $field->default_value();
 $this->write_data($field->type(), $value, $encoder);
```

This is running in PHP 8.1.3 using avro-sede-php 1.7.1 and running via the AvroSerDeEncoder symfony serializer.

**Comment by DBTK1990** [comment]
when this issue is going to get fixed?
i have run into problems with that too
every other platform support it except in php
please help fix or give permission to give u a pull request

**Comment by axelrtgs** [comment]
Hello @tPl0ch @fcoedno , 

I was wondering if there was a chance that someone could have a look at the upstream PR and merge then update the dependency here to fix the bug.

Thank you kindly
