### ISSUE TITLE
String representation of avro schema is not correct (flix-tech/avro-php)

### ISSUE THREAD

**Issue by varunkamra** [flix-tech/avro-serde-php#68]
Background: I have a java application which uses Java kafka client and avro packages to register a schema. The messages to that schema will be pushed to the topic using a PHP application.

Issue: Before producing a kafka message following API is being called to determine the schemaId of the schema we wish to produce message to. The current API call being sent from flix-tech/schema-registry-php-client resembles the following:

```
POST /subjects/test HTTP/1.1
Host: schemaregistry.example.com
Accept: application/vnd.schemaregistry.v1+json
{"schema":"{\"type\":\"record\",\"name\":\"test\",\"fields\":[{\"type\":\"string\",\"name\":\"field1\"},{\"type\":\"int\",\"name\":\"field2\"}]}"}
```

This results in an error from kafka schema registry `40403 schema not found`

The above API call is being sent from here:
https://github.com/flix-tech/schema-registry-php-client/blob/ad1a7960731fa2b4f8a0708286368b4b21a0ad40/src/Requests/Functions.php#L76

The schema string used in the above API call is being generated in flix-tech/avro-php package is from this function which simply uses json_encode on the avro object.
https://github.com/flix-tech/avro-php/blob/0eadbc19f3e0f79804d73b71f8c3e309a37efe77/lib/avro/schema.php#L548

The ideal way of sending the above API call is following which uses a proper formatted json string according to confluent doc:

```
POST /subjects/test HTTP/1.1
Host: schemaregistry.example.com
Accept: application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json

{
      "schema":
         "{
                \"type\": \"record\",
                \"name\": \"test\",
                \"fields\":
                  [
                    {
                      \"type\": \"string\",
                      \"name\": \"field1\"
                    },
                    {
                      \"type\": \"int\",
                      \"name\": \"field2\"
                    }
                  ]
              }"
    }
```
https://docs.confluent.io/3.0.0/schema-registry/docs/api.html
The above API call works fine with correct json encoded formatting.

I had to extend AvroSchema class to define a static variable called $json which is initialized in parse function
https://github.com/flix-tech/avro-php/blob/0eadbc19f3e0f79804d73b71f8c3e309a37efe77/lib/avro/schema.php#L307

and for returning the schema from __toString I am simply returning the static variable value. Could you please add a proper fix for this? Also, I believe the schema should be registered with same format as well.

Avro producer being used for the PHP application is
https://github.com/jobcloud/php-kafka-lib

@nick-zh

**Comment by tPl0ch** [comment]
There is no difference between the current format and the formatted one, other than useless white spaces that takes useless bandwidth. From a JSON standard perspective your example and the actual sent data are equivalent.
