### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by rameshvenk** [flix-tech/avro-serde-php#76]
## Environment
* Confluent Kafka running on Confluent Cloud
* php 8.2.5 running on macOS M1 
* librdkafka: stable 2.1.0 from homebrew
* rdkafka 6.0.3 from pecl
* flix-tech/avro-serde-php version 1.7.2
* jobcloud/php-kafka-lib version 2.0.0

The following deprecation warnings were printed when trying to consume messages from a Kafka topic that had Avro messages. There is no loss of functionality, merely these warnings. I presume at some point they will turn into errors, and hence this is being reported.

```
Deprecated: Creation of dynamic property AvroPrimitiveSchema::$type is deprecated in /tmp/php/vendor/flix-tech/avro-php/lib/avro/schema.php on line 486
Deprecated: Creation of dynamic property AvroPrimitiveSchema::$logical_type is deprecated in /tmp/php/vendor/flix-tech/avro-php/lib/avro/schema.php on line 491
PHP Deprecated:  Creation of dynamic property AvroPrimitiveSchema::$extra_attributes is deprecated in /tmp/php/vendor/flix-tech/avro-php/lib/avro/schema.php on line 492
PHP Deprecated:  Creation of dynamic property AvroField::$type is deprecated in /tmp/php/vendor/flix-tech/avro-php/lib/avro/schema.php on line 1560
```

**Comment by nemanjajojic** [comment]
Yup. the same here. is there any roadmap for this?

**Comment by rameshvenk** [comment]
I noticed that version `2.0.0` of `flix-tech/avro-serde-php` was just released, so I tested with that, and the deprecation warnings are gone. From my point of view, this can be closed.

**Comment by nemanjajojic** [comment]
no more warning with version 2 👍
